'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class EMPRESAS
    Public Property EmpresaID As Integer
    Public Property EmpresaNombre As String
    Public Property EmpresaEstado As String

    Public Overridable Property PERSONA As ICollection(Of PERSONA) = New HashSet(Of PERSONA)
    Public Overridable Property TIPODOCUMENTO As ICollection(Of TIPODOCUMENTO) = New HashSet(Of TIPODOCUMENTO)
    Public Overridable Property UBICACION As ICollection(Of UBICACION) = New HashSet(Of UBICACION)

End Class
