'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class SOLUTIONEntities1
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=SOLUTIONEntities1")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property EMPRESAS() As DbSet(Of EMPRESAS)
    Public Overridable Property PERSONA() As DbSet(Of PERSONA)
    Public Overridable Property TIPODOCUMENTO() As DbSet(Of TIPODOCUMENTO)
    Public Overridable Property UBICACION() As DbSet(Of UBICACION)

End Class
