'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PERSONA
    Public Property PersonaID As Integer
    Public Property PersonaNombre As String
    Public Property PersonaApelliso As String
    Public Property PersonaNroDocumento As String
    Public Property EmpresaID As Integer
    Public Property TipoDocumentoID As Integer

    Public Overridable Property EMPRESAS As EMPRESAS
    Public Overridable Property TIPODOCUMENTO As TIPODOCUMENTO
    Public Overridable Property UBICACION As ICollection(Of UBICACION) = New HashSet(Of UBICACION)

End Class
