'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TIPODOCUMENTO
    Public Property TipoDocumentoID As Integer
    Public Property TipoDocumentoNombre As String
    Public Property EmpresaID As Integer

    Public Overridable Property EMPRESAS As EMPRESAS
    Public Overridable Property PERSONA As ICollection(Of PERSONA) = New HashSet(Of PERSONA)

End Class
