'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class UBICACION
    Public Property UbicacionID As Integer
    Public Property UbicacionLongitud As String
    Public Property UbicacionLatitud As String
    Public Property UbicacionObservaciones As String
    Public Property PersonaID As Integer
    Public Property EmpresaID As Integer

    Public Overridable Property EMPRESAS As EMPRESAS
    Public Overridable Property PERSONA As PERSONA

End Class
